#ifndef ABB_RAPID_CODE_DEFINITIONS_H
#define ABB_RAPID_CODE_DEFINITIONS_H

#define ROBOT_PING_CODE 0
#define ROBOT_MOVE_CARTESIAN_CODE 1
#define ROBOT_MOVE_JOINT_CODE 2
#define ROBOT_GET_CARTESIAN_CODE 3
#define ROBOT_GET_JOINT_CODE 4
#define ROBOT_GET_EXTERNAL_JOINT_CODE 5
#define ROBOT_SET_TOOL_CODE 6
#define ROBOT_SET_WOBJ_CODE 7
#define ROBOT_SET_SPEED_CODE 8
#define ROBOT_SET_ZONE_CODE 9
#define ROBOT_SET_VACUUM 11
#define ROBOT_ADD_CARTESIAN_BUFFER_CODE 30
#define ROBOT_CLEAR_CARTESIAN_BUFFER_CODE 31
#define ROBOT_GET_CARTESIAN_BUFFER_SIZE_CODE 32
#define ROBOT_EXCECUTE_CARTESIAN_BUFFEER_CODE 33
#define ROBOT_MOVE_EXTERNAL_AXIS_CODE 34
#define ROBOT_SET_CIRCUAL_MIDPT_CODE 35
#define ROBOT_SET_CIRCUAL_TO_PT_CODE 36
#define ROBOT_GET_INFO 98
#define ROBOT_CLOSE_CONNECTION 99

#endif // ABB_RAPID_CODE_DEFINITIONS_H
