controller_list:
  - name: fake_flange_planning_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_mat_to_tool_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
#  - group: flange_planning
#    pose: home

  []