// Generated by gencpp from file abb_node/robot_SetCartesian.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_SETCARTESIAN_H
#define ABB_NODE_MESSAGE_ROBOT_SETCARTESIAN_H

#include <ros/service_traits.h>


#include <abb_node/robot_SetCartesianRequest.h>
#include <abb_node/robot_SetCartesianResponse.h>


namespace abb_node
{

struct robot_SetCartesian
{

typedef robot_SetCartesianRequest Request;
typedef robot_SetCartesianResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetCartesian
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_SetCartesian > {
  static const char* value()
  {
    return "4aa959d966f8a29fdd7f035d2997b10c";
  }

  static const char* value(const ::abb_node::robot_SetCartesian&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_SetCartesian > {
  static const char* value()
  {
    return "abb_node/robot_SetCartesian";
  }

  static const char* value(const ::abb_node::robot_SetCartesian&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_SetCartesianRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_SetCartesian >
template<>
struct MD5Sum< ::abb_node::robot_SetCartesianRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetCartesian >::value();
  }
  static const char* value(const ::abb_node::robot_SetCartesianRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetCartesianRequest> should match
// service_traits::DataType< ::abb_node::robot_SetCartesian >
template<>
struct DataType< ::abb_node::robot_SetCartesianRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetCartesian >::value();
  }
  static const char* value(const ::abb_node::robot_SetCartesianRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_SetCartesianResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_SetCartesian >
template<>
struct MD5Sum< ::abb_node::robot_SetCartesianResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetCartesian >::value();
  }
  static const char* value(const ::abb_node::robot_SetCartesianResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetCartesianResponse> should match
// service_traits::DataType< ::abb_node::robot_SetCartesian >
template<>
struct DataType< ::abb_node::robot_SetCartesianResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetCartesian >::value();
  }
  static const char* value(const ::abb_node::robot_SetCartesianResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_SETCARTESIAN_H
