// Generated by gencpp from file abb_node/robot_Stop.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_STOP_H
#define ABB_NODE_MESSAGE_ROBOT_STOP_H

#include <ros/service_traits.h>


#include <abb_node/robot_StopRequest.h>
#include <abb_node/robot_StopResponse.h>


namespace abb_node
{

struct robot_Stop
{

typedef robot_StopRequest Request;
typedef robot_StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_Stop
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_Stop > {
  static const char* value()
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const ::abb_node::robot_Stop&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_Stop > {
  static const char* value()
  {
    return "abb_node/robot_Stop";
  }

  static const char* value(const ::abb_node::robot_Stop&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_StopRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_Stop >
template<>
struct MD5Sum< ::abb_node::robot_StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_Stop >::value();
  }
  static const char* value(const ::abb_node::robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_StopRequest> should match
// service_traits::DataType< ::abb_node::robot_Stop >
template<>
struct DataType< ::abb_node::robot_StopRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_Stop >::value();
  }
  static const char* value(const ::abb_node::robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_StopResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_Stop >
template<>
struct MD5Sum< ::abb_node::robot_StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_Stop >::value();
  }
  static const char* value(const ::abb_node::robot_StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_StopResponse> should match
// service_traits::DataType< ::abb_node::robot_Stop >
template<>
struct DataType< ::abb_node::robot_StopResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_Stop >::value();
  }
  static const char* value(const ::abb_node::robot_StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_STOP_H
