// Generated by gencpp from file abb_node/robot_SetTool.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_SETTOOL_H
#define ABB_NODE_MESSAGE_ROBOT_SETTOOL_H

#include <ros/service_traits.h>


#include <abb_node/robot_SetToolRequest.h>
#include <abb_node/robot_SetToolResponse.h>


namespace abb_node
{

struct robot_SetTool
{

typedef robot_SetToolRequest Request;
typedef robot_SetToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetTool
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_SetTool > {
  static const char* value()
  {
    return "13716a3f1e232bc5200a276031ef97c2";
  }

  static const char* value(const ::abb_node::robot_SetTool&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_SetTool > {
  static const char* value()
  {
    return "abb_node/robot_SetTool";
  }

  static const char* value(const ::abb_node::robot_SetTool&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_SetToolRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_SetTool >
template<>
struct MD5Sum< ::abb_node::robot_SetToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetTool >::value();
  }
  static const char* value(const ::abb_node::robot_SetToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetToolRequest> should match
// service_traits::DataType< ::abb_node::robot_SetTool >
template<>
struct DataType< ::abb_node::robot_SetToolRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetTool >::value();
  }
  static const char* value(const ::abb_node::robot_SetToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_SetToolResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_SetTool >
template<>
struct MD5Sum< ::abb_node::robot_SetToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetTool >::value();
  }
  static const char* value(const ::abb_node::robot_SetToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetToolResponse> should match
// service_traits::DataType< ::abb_node::robot_SetTool >
template<>
struct DataType< ::abb_node::robot_SetToolResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetTool >::value();
  }
  static const char* value(const ::abb_node::robot_SetToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_SETTOOL_H
