// Generated by gencpp from file abb_node/robot_SetZone.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_SETZONE_H
#define ABB_NODE_MESSAGE_ROBOT_SETZONE_H

#include <ros/service_traits.h>


#include <abb_node/robot_SetZoneRequest.h>
#include <abb_node/robot_SetZoneResponse.h>


namespace abb_node
{

struct robot_SetZone
{

typedef robot_SetZoneRequest Request;
typedef robot_SetZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetZone
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_SetZone > {
  static const char* value()
  {
    return "9a8139bbede588258d8a8cdc808e7b88";
  }

  static const char* value(const ::abb_node::robot_SetZone&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_SetZone > {
  static const char* value()
  {
    return "abb_node/robot_SetZone";
  }

  static const char* value(const ::abb_node::robot_SetZone&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_SetZoneRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_SetZone >
template<>
struct MD5Sum< ::abb_node::robot_SetZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetZone >::value();
  }
  static const char* value(const ::abb_node::robot_SetZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetZoneRequest> should match
// service_traits::DataType< ::abb_node::robot_SetZone >
template<>
struct DataType< ::abb_node::robot_SetZoneRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetZone >::value();
  }
  static const char* value(const ::abb_node::robot_SetZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_SetZoneResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_SetZone >
template<>
struct MD5Sum< ::abb_node::robot_SetZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetZone >::value();
  }
  static const char* value(const ::abb_node::robot_SetZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetZoneResponse> should match
// service_traits::DataType< ::abb_node::robot_SetZone >
template<>
struct DataType< ::abb_node::robot_SetZoneResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetZone >::value();
  }
  static const char* value(const ::abb_node::robot_SetZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_SETZONE_H
