// Generated by gencpp from file abb_node/robot_SetJoints.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_SETJOINTS_H
#define ABB_NODE_MESSAGE_ROBOT_SETJOINTS_H

#include <ros/service_traits.h>


#include <abb_node/robot_SetJointsRequest.h>
#include <abb_node/robot_SetJointsResponse.h>


namespace abb_node
{

struct robot_SetJoints
{

typedef robot_SetJointsRequest Request;
typedef robot_SetJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetJoints
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_SetJoints > {
  static const char* value()
  {
    return "23982c479cd3fc1d1b9c7ca9addbaa85";
  }

  static const char* value(const ::abb_node::robot_SetJoints&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_SetJoints > {
  static const char* value()
  {
    return "abb_node/robot_SetJoints";
  }

  static const char* value(const ::abb_node::robot_SetJoints&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_SetJointsRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_SetJoints >
template<>
struct MD5Sum< ::abb_node::robot_SetJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetJoints >::value();
  }
  static const char* value(const ::abb_node::robot_SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetJointsRequest> should match
// service_traits::DataType< ::abb_node::robot_SetJoints >
template<>
struct DataType< ::abb_node::robot_SetJointsRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetJoints >::value();
  }
  static const char* value(const ::abb_node::robot_SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_SetJointsResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_SetJoints >
template<>
struct MD5Sum< ::abb_node::robot_SetJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetJoints >::value();
  }
  static const char* value(const ::abb_node::robot_SetJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetJointsResponse> should match
// service_traits::DataType< ::abb_node::robot_SetJoints >
template<>
struct DataType< ::abb_node::robot_SetJointsResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetJoints >::value();
  }
  static const char* value(const ::abb_node::robot_SetJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_SETJOINTS_H
