// Generated by gencpp from file abb_node/robot_SetWorkObject.msg
// DO NOT EDIT!


#ifndef ABB_NODE_MESSAGE_ROBOT_SETWORKOBJECT_H
#define ABB_NODE_MESSAGE_ROBOT_SETWORKOBJECT_H

#include <ros/service_traits.h>


#include <abb_node/robot_SetWorkObjectRequest.h>
#include <abb_node/robot_SetWorkObjectResponse.h>


namespace abb_node
{

struct robot_SetWorkObject
{

typedef robot_SetWorkObjectRequest Request;
typedef robot_SetWorkObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetWorkObject
} // namespace abb_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_node::robot_SetWorkObject > {
  static const char* value()
  {
    return "13716a3f1e232bc5200a276031ef97c2";
  }

  static const char* value(const ::abb_node::robot_SetWorkObject&) { return value(); }
};

template<>
struct DataType< ::abb_node::robot_SetWorkObject > {
  static const char* value()
  {
    return "abb_node/robot_SetWorkObject";
  }

  static const char* value(const ::abb_node::robot_SetWorkObject&) { return value(); }
};


// service_traits::MD5Sum< ::abb_node::robot_SetWorkObjectRequest> should match
// service_traits::MD5Sum< ::abb_node::robot_SetWorkObject >
template<>
struct MD5Sum< ::abb_node::robot_SetWorkObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetWorkObject >::value();
  }
  static const char* value(const ::abb_node::robot_SetWorkObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetWorkObjectRequest> should match
// service_traits::DataType< ::abb_node::robot_SetWorkObject >
template<>
struct DataType< ::abb_node::robot_SetWorkObjectRequest>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetWorkObject >::value();
  }
  static const char* value(const ::abb_node::robot_SetWorkObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_node::robot_SetWorkObjectResponse> should match
// service_traits::MD5Sum< ::abb_node::robot_SetWorkObject >
template<>
struct MD5Sum< ::abb_node::robot_SetWorkObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_node::robot_SetWorkObject >::value();
  }
  static const char* value(const ::abb_node::robot_SetWorkObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_node::robot_SetWorkObjectResponse> should match
// service_traits::DataType< ::abb_node::robot_SetWorkObject >
template<>
struct DataType< ::abb_node::robot_SetWorkObjectResponse>
{
  static const char* value()
  {
    return DataType< ::abb_node::robot_SetWorkObject >::value();
  }
  static const char* value(const ::abb_node::robot_SetWorkObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_NODE_MESSAGE_ROBOT_SETWORKOBJECT_H
