gazebo_ros_control/pid_gains:

  joint_1: {p: 1.0, i: 0.0, d: 1.0}
  joint_2: {p: 1.0, i: 0.0, d: 1.0}
  joint_3: {p: 1.0, i: 0.0, d: 1.0}
  joint_4: {p: 1.0, i: 0.0, d: 1.0}
  joint_5: {p: 1.0, i: 0.0, d: 1.0}
  joint_6: {p: 1.0, i: 0.0, d: 1.0}
